### ISSUE TITLE
All db query involving user input must be prepared.

### ISSUE THREAD

**Issue by xinan** [hong-lu/Blog#13]
You are interpolating user inputs directly into your sql statement, which is very vulnerable to sql injection. 
For example, when submit a registration, you pass the username to checkUname, and the query is 
`$stmt = "SELECT * FROM users WHERE user_name = '$new_uname' ";`
What if I enter my username as `1'; DROP TABLE 'users`? I just dropped your users table. 

Note that it is not enough to just have a front-end validation, because I can always bypass front-end validation by sending POST request directly to your create_user.php.

**Comment by hong-lu** [comment]
Thx for bringing this up, only when u bypass front-end validation can u enter ur username like that. I didn't notice that one can send POST request directly to my create_user page. Can show me an example how?

**Comment by xinan** [comment]
That's easy. You can use command line tools like `telnet`. 

One even easier way is to create a customised html form by myself, then submit it to your php lol.
